/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordsRouteImport } from './routes/words'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordsIndexRouteImport } from './routes/words/index'
import { Route as WordsSummaryRouteImport } from './routes/words/summary'

const WordsRoute = WordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsIndexRoute = WordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WordsRoute,
} as any)
const WordsSummaryRoute = WordsSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => WordsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/words': typeof WordsRouteWithChildren
  '/words/summary': typeof WordsSummaryRoute
  '/words/': typeof WordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/words/summary': typeof WordsSummaryRoute
  '/words': typeof WordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/words': typeof WordsRouteWithChildren
  '/words/summary': typeof WordsSummaryRoute
  '/words/': typeof WordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/words' | '/words/summary' | '/words/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/words/summary' | '/words'
  id: '__root__' | '/' | '/about' | '/words' | '/words/summary' | '/words/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  WordsRoute: typeof WordsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/': {
      id: '/words/'
      path: '/'
      fullPath: '/words/'
      preLoaderRoute: typeof WordsIndexRouteImport
      parentRoute: typeof WordsRoute
    }
    '/words/summary': {
      id: '/words/summary'
      path: '/summary'
      fullPath: '/words/summary'
      preLoaderRoute: typeof WordsSummaryRouteImport
      parentRoute: typeof WordsRoute
    }
  }
}

interface WordsRouteChildren {
  WordsSummaryRoute: typeof WordsSummaryRoute
  WordsIndexRoute: typeof WordsIndexRoute
}

const WordsRouteChildren: WordsRouteChildren = {
  WordsSummaryRoute: WordsSummaryRoute,
  WordsIndexRoute: WordsIndexRoute,
}

const WordsRouteWithChildren = WordsRoute._addFileChildren(WordsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  WordsRoute: WordsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
